### ISSUE TITLE
Can't get access token

### ISSUE THREAD

**Issue by footniko** [Jumplead/api-documentation#1]
Hello!
How can I get access token, do you have any examples? I've tried various attempts, like following:
```curl -v -i -H "Accept:application/json" -H "Content-Type:application/json" "https://account.mooloop.com/oauth/access_token" -XPOST -d '{"redirect_uri":"MY_CALLBACK_URI", "grant_type":"refresh_token", "client_id":"MY_CLIENT_ID", "client_secret":"MY_CLIENT_SECRET", "code":"code"}'```
but got different errors. Could you provide any example please?

**Comment by adamlc** [comment]
@footniko can you contact Jumplead support? We dont answer support queries here. We use a standard OAuth2 API, so should be the same as facebook, github etc
